# Terraform Variables
# Generated by InfrastructureAgent

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "q2o"
}

variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "East US"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "production"
}

variable "allowed_countries" {
  description = "List of allowed countries for geo-filtering"
  type        = list(string)
  default     = ["US", "CA", "GB", "JM"]
}

variable "ip_allowlist" {
  description = "List of allowed IP addresses"
  type        = list(string)
  default     = []
}

variable "alert_email" {
  description = "Email address for alerts"
  type        = string
  default     = "admin@quick2odoo.online"
}
