# Azure Front Door WAF Configuration
# Generated by InfrastructureAgent

resource "azurerm_frontdoor_firewall_policy" "q2o_waf" {
  name                = "${var.project_name}-waf-policy"
  resource_group_name = azurerm_resource_group.main.name
  location            = "Global"

  enabled = true

  # OWASP ruleset
  custom_rule {
    name     = "OWASP"
    priority = 1
    rule_type = "MatchRule"
    enabled   = true

    match_conditions {
      match_variables {
        variable_name = "RequestMethod"
      }
      operator = "Equal"
      values    = ["POST", "PUT", "DELETE"]
    }

    action = "Block"
  }

  # Rate limiting
  custom_rule {
    name     = "RateLimit"
    priority = 2
    rule_type = "RateLimitRule"
    enabled   = true
    rate_limit_duration_in_minutes = 1
    rate_limit_threshold            = 100

    match_conditions {
      match_variables {
        variable_name = "RemoteAddr"
      }
      operator = "IPMatch"
      values    = ["*"]
    }

    action = "Block"
  }

  # Geo filtering
  custom_rule {
    name     = "GeoFilter"
    priority = 3
    rule_type = "MatchRule"
    enabled   = true

    match_conditions {
      match_variables {
        variable_name = "RemoteAddr"
      }
      operator = "GeoMatch"
      values   = var.allowed_countries
    }

    action = "Allow"
  }

  # Allow Stripe webhook path
  custom_rule {
    name     = "AllowStripeWebhook"
    priority = 10
    rule_type = "MatchRule"
    enabled   = true

    match_conditions {
      match_variables {
        variable_name = "RequestUri"
      }
      operator = "Contains"
      values    = ["/api/billing/webhook"]
    }

    action = "Allow"
  }

  # IP allowlist (if specified)
  dynamic "custom_rule" {
    for_each = length(var.ip_allowlist) > 0 ? [1] : []
    content {
      name     = "IPAllowlist"
      priority = 20
      rule_type = "MatchRule"
      enabled   = true

      match_conditions {
        match_variables {
          variable_name = "RemoteAddr"
        }
        operator = "IPMatch"
        values    = var.ip_allowlist
      }

      action = "Allow"
    }
  }
}

output "waf_policy_id" {
  value = azurerm_frontdoor_firewall_policy.q2o_waf.id
}
