"""
Temporal Backfill Workflow
Generated by WorkflowAgent
"""

from temporalio import workflow
from typing import List, Dict, Any
import logging

logger = logging.getLogger(__name__)


@workflow.defn
class BackfillWorkflow:
    """
    Workflow for syncing entities from QuickBooks to Odoo
    """
    
    @workflow.run
    async def run(self, tenant_id: str, entity_types: List[str]) -> Dict[str, Any]:
        """
        Run backfill workflow.
        
        Args:
            tenant_id: Tenant ID
            entity_types: List of entity types to sync
            
        Returns:
            Workflow result
        """
        logger.info(f"Starting backfill workflow for tenant {tenant_id}")
        
        results = {}
        
        for entity_type in entity_types:
            try:
                # Fetch entities from QuickBooks
                qbo_entities = await workflow.execute_activity(
                    fetch_qbo_entities,
                    args=[tenant_id, entity_type],
                    start_to_close_timeout=300,
                )
                
                # Upsert to Odoo
                result = await workflow.execute_activity(
                    upsert_odoo_entities,
                    args=[tenant_id, entity_type, qbo_entities],
                    start_to_close_timeout=600,
                )
                
                results[entity_type] = {
                    "status": "success",
                    "count": len(qbo_entities),
                    "result": result
                }
                
            except Exception as e:
                logger.error(f"Error syncing {entity_type}: {str(e)}")
                results[entity_type] = {
                    "status": "failed",
                    "error": str(e)
                }
        
        return {
            "tenant_id": tenant_id,
            "results": results
        }


# Import activity functions (defined in activities)
from ..activities.entities import fetch_qbo_entities, upsert_odoo_entities
