"""
QuickBooks Online API Client
Generated by IntegrationAgent
"""

import requests
from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)

QBO_API_BASE = "https://sandbox-quickbooks.api.intuit.com/v3"  # Use production URL for live


class QBOClient:
    """
    QuickBooks Online API client
    """
    
    def __init__(self, realm_id: str, access_token: str):
        """
        Initialize QBO client.
        
        Args:
            realm_id: QuickBooks company ID
            access_token: OAuth access token
        """
        self.realm_id = realm_id
        self.access_token = access_token
        self.base_url = QBO_API_BASE
        self.headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Accept": "application/json",
            "Content-Type": "application/json"
        }
    
    def _make_request(self, method: str, endpoint: str, data: Optional[Dict] = None) -> Dict:
        """
        Make API request to QuickBooks.
        
        Args:
            method: HTTP method
            endpoint: API endpoint
            data: Request body data
            
        Returns:
            Response JSON
        """
        url = f"{self.base_url}/company/{self.realm_id}/{endpoint}"
        
        response = requests.request(
            method=method,
            url=url,
            headers=self.headers,
            json=data
        )
        
        response.raise_for_status()
        return response.json()
    
    def get_company_info(self) -> Dict:
        """Get company information."""
        return self._make_request("GET", "companyinfo")
    
    def query(self, query: str) -> List[Dict]:
        """
        Execute QuickBooks query.
        
        Args:
            query: QuickBooks query string (SQL-like)
            
        Returns:
            List of entities
        """
        response = self._make_request("GET", f"query?query={query}")
        return response.get("QueryResponse", {}).get("entities", [])
    
    def get_customers(self) -> List[Dict]:
        """Get all customers."""
        return self.query("SELECT * FROM Customer")
    
    def get_items(self) -> List[Dict]:
        """Get all items."""
        return self.query("SELECT * FROM Item")
    
    def get_invoices(self, start_date: Optional[str] = None) -> List[Dict]:
        """Get invoices, optionally filtered by start date."""
        query = "SELECT * FROM Invoice"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        return self.query(query)
    
    def create_invoice(self, invoice_data: Dict) -> Dict:
        """Create an invoice."""
        response = self._make_request("POST", "invoice", {"Invoice": invoice_data})
        return response.get("Invoice", {})
    
    def update_entity(self, entity_type: str, entity_id: str, sync_token: str, data: Dict) -> Dict:
        """
        Update an entity.
        
        Args:
            entity_type: Entity type (e.g., "Customer", "Invoice")
            entity_id: Entity ID
            sync_token: Sync token from previous read
            data: Updated entity data
            
        Returns:
            Updated entity
        """
        endpoint = entity_type.lower()
        data["Id"] = entity_id
        data["SyncToken"] = sync_token
        response = self._make_request("POST", endpoint, {entity_type: data})
        return response.get(entity_type, {})

