-- Research Tables Migration
-- Adds research_results and research_analytics tables to PostgreSQL
-- Run this to enable database-backed research storage

-- Research Results Table
CREATE TABLE IF NOT EXISTS research_results (
    id SERIAL PRIMARY KEY,
    research_id VARCHAR(64) UNIQUE NOT NULL,
    
    -- Query information
    query TEXT NOT NULL,
    query_hash VARCHAR(64) NOT NULL,
    project_name VARCHAR(255),
    project_id VARCHAR(64),
    
    -- Research content (JSON)
    search_results JSONB,
    documentation_urls JSONB,
    code_examples JSONB,
    key_findings JSONB,
    
    -- Quality metrics
    confidence_score FLOAT DEFAULT 0.0,
    results_count INTEGER DEFAULT 0,
    
    -- Metadata
    research_depth VARCHAR(50),
    cached BOOLEAN DEFAULT FALSE,
    llm_synthesized BOOLEAN DEFAULT FALSE,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_accessed TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    
    -- Usage tracking
    access_count INTEGER DEFAULT 0,
    
    -- Full-text search
    full_content TEXT
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_research_query_hash ON research_results(query_hash);
CREATE INDEX IF NOT EXISTS idx_research_project ON research_results(project_id, project_name);
CREATE INDEX IF NOT EXISTS idx_research_created ON research_results(created_at);
CREATE INDEX IF NOT EXISTS idx_research_expires ON research_results(expires_at);
CREATE INDEX IF NOT EXISTS idx_research_query_text ON research_results USING gin(to_tsvector('english', query));
CREATE INDEX IF NOT EXISTS idx_research_full_text ON research_results USING gin(to_tsvector('english', full_content));

-- Research Analytics Table
CREATE TABLE IF NOT EXISTS research_analytics (
    id SERIAL PRIMARY KEY,
    research_id VARCHAR(64) NOT NULL,
    
    -- Usage information
    used_by_agent_type VARCHAR(50),
    used_by_agent_id VARCHAR(100),
    used_for_task_id VARCHAR(100),
    
    -- Effectiveness tracking
    was_helpful BOOLEAN,
    helpfulness_score FLOAT,
    
    -- Timestamp
    used_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for analytics
CREATE INDEX IF NOT EXISTS idx_analytics_research ON research_analytics(research_id);
CREATE INDEX IF NOT EXISTS idx_analytics_agent ON research_analytics(used_by_agent_type, used_by_agent_id);
CREATE INDEX IF NOT EXISTS idx_analytics_used_at ON research_analytics(used_at);

-- Grant permissions (adjust based on your setup)
-- GRANT ALL ON research_results TO q2o_user;
-- GRANT ALL ON research_analytics TO q2o_user;
-- GRANT USAGE, SELECT ON SEQUENCE research_results_id_seq TO q2o_user;
-- GRANT USAGE, SELECT ON SEQUENCE research_analytics_id_seq TO q2o_user;

-- Comments for documentation
COMMENT ON TABLE research_results IS 'Stores research findings from ResearcherAgent with LLM synthesis';
COMMENT ON COLUMN research_results.llm_synthesized IS 'Whether key_findings were generated by LLM (vs basic keyword analysis)';
COMMENT ON COLUMN research_results.full_content IS 'Full-text searchable content for similarity matching';
COMMENT ON TABLE research_analytics IS 'Tracks research usage and effectiveness across projects';

