/**
 * Onboarding Wizard Page
 * Generated by FrontendAgent
 */

import { useState } from "react";
import { NextPage } from "next";
import axios from "axios";

const OnboardingPage: NextPage = () => {
  const [step, setStep] = useState(1);
  const [qboConnected, setQboConnected] = useState(false);
  const [odooUrl, setOdooUrl] = useState("");
  const [odooApiKey, setOdooApiKey] = useState("");
  const [odooDatabase, setOdooDatabase] = useState("");
  const [odooConnected, setOdooConnected] = useState(false);
  const [testing, setTesting] = useState(false);
  const [error, setError] = useState("");

  const testQBO = async () => {
    try {
      setTesting(true);
      const response = await axios.get("/api/connect/qbo/test");
      if (response.data.status === "success") {
        setQboConnected(true);
        setStep(2);
      }
    } catch (err: any) {
      setError(err.response?.data?.error || "Failed to connect to QuickBooks");
    } finally {
      setTesting(false);
    }
  };

  const saveOdoo = async () => {
    try {
      setTesting(true);
      const response = await axios.post("/api/connect/odoo/save", {
        url: odooUrl,
        api_key: odooApiKey,
        database: odooDatabase,
      });
      if (response.data.status === "success") {
        setOdooConnected(true);
      }
    } catch (err: any) {
      setError(err.response?.data?.error || "Failed to save Odoo connection");
    } finally {
      setTesting(false);
    }
  };

  const testOdoo = async () => {
    try {
      setTesting(true);
      const response = await axios.post("/api/connect/odoo/test", {
        url: odooUrl,
        api_key: odooApiKey,
        database: odooDatabase,
      });
      if (response.data.status === "success") {
        setOdooConnected(true);
        setStep(3);
      }
    } catch (err: any) {
      setError(err.response?.data?.error || "Failed to test Odoo connection");
    } finally {
      setTesting(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Welcome to Quick2Odoo</h1>
      
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      <div className="max-w-2xl mx-auto">
        {/* Step 1: QuickBooks Connection */}
        {step === 1 && (
          <div className="bg-white shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-semibold mb-4">Step 1: Connect QuickBooks</h2>
            <p className="text-gray-600 mb-4">
              Connect your QuickBooks Online account to get started.
            </p>
            <button
              onClick={testQBO}
              disabled={testing}
              className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
            >
              {testing ? "Connecting..." : "Connect QuickBooks"}
            </button>
            {qboConnected && (
              <div className="mt-4 text-green-600">
                ✓ QuickBooks connected successfully
              </div>
            )}
          </div>
        )}

        {/* Step 2: Save Odoo Connection */}
        {step === 2 && (
          <div className="bg-white shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-semibold mb-4">Step 2: Connect Odoo</h2>
            <p className="text-gray-600 mb-4">
              Enter your Odoo v18 connection details.
            </p>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Odoo URL
                </label>
                <input
                  type="text"
                  value={odooUrl}
                  onChange={(e) => setOdooUrl(e.target.value)}
                  placeholder="https://your-odoo-instance.com"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Database
                </label>
                <input
                  type="text"
                  value={odooDatabase}
                  onChange={(e) => setOdooDatabase(e.target.value)}
                  placeholder="database_name"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  API Key
                </label>
                <input
                  type="password"
                  value={odooApiKey}
                  onChange={(e) => setOdooApiKey(e.target.value)}
                  placeholder="your-api-key"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md"
                />
              </div>
            </div>

            <div className="mt-6 flex gap-4">
              <button
                onClick={saveOdoo}
                disabled={testing || !odooUrl || !odooDatabase || !odooApiKey}
                className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
              >
                {testing ? "Saving..." : "Save Connection"}
              </button>
              
              <button
                onClick={testOdoo}
                disabled={testing || !odooUrl || !odooDatabase || !odooApiKey}
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
              >
                {testing ? "Testing..." : "Test Connection"}
              </button>
            </div>

            {odooConnected && (
              <div className="mt-4 text-green-600">
                ✓ Odoo connected successfully
              </div>
            )}
          </div>
        )}

        {/* Step 3: Completion */}
        {step === 3 && (
          <div className="bg-white shadow-md rounded-lg p-6">
            <h2 className="text-2xl font-semibold mb-4">Setup Complete!</h2>
            <p className="text-gray-600 mb-4">
              Your QuickBooks and Odoo connections are configured. You can now start syncing data.
            </p>
            <a
              href="/mappings"
              className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded inline-block"
            >
              Go to Mappings
            </a>
          </div>
        )}
      </div>
    </div>
  );
};

export default OnboardingPage;
