"""
VCS Integration - GitHub API integration for PR creation.
"""

import logging
import os
import json
from typing import Dict, Any, Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)


class VCSIntegration:
    """Handles VCS operations including PR creation via GitHub API."""
    
    def __init__(self, workspace_path: str = "."):
        self.workspace_path = workspace_path
        self.github_token = os.getenv("GITHUB_TOKEN")
        self.github_repo = os.getenv("GITHUB_REPO")  # Format: owner/repo
        self.github_api_base = "https://api.github.com"
    
    def create_pull_request(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str = "main"
    ) -> Optional[Dict[str, Any]]:
        """
        Create a pull request on GitHub.
        
        Args:
            title: PR title
            body: PR description
            head_branch: Source branch
            base_branch: Target branch (default: main)
            
        Returns:
            PR information dict or None if failed
        """
        if not self.github_token or not self.github_repo:
            logger.warning("GitHub token or repo not configured. Skipping PR creation.")
            return None
        
        try:
            import httpx
            
            url = f"{self.github_api_base}/repos/{self.github_repo}/pulls"
            headers = {
                "Authorization": f"token {self.github_token}",
                "Accept": "application/vnd.github.v3+json",
                "Content-Type": "application/json"
            }
            
            payload = {
                "title": title,
                "body": body,
                "head": head_branch,
                "base": base_branch
            }
            
            response = httpx.post(url, headers=headers, json=payload, timeout=30)
            
            if response.status_code == 201:
                pr_data = response.json()
                logger.info(f"Created PR #{pr_data['number']}: {title}")
                return pr_data
            else:
                logger.error(f"Failed to create PR: {response.status_code} - {response.text}")
                return None
        except ImportError:
            logger.error("httpx not available. Install with: pip install httpx")
            return None
        except Exception as e:
            logger.error(f"Error creating PR: {e}", exc_info=True)
            return None
    
    def create_project_pr(
        self,
        project_description: str,
        objectives: List[str],
        branch_name: str,
        base_branch: str = "main",
        files_created: Optional[List[str]] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Create a PR for a completed project.
        
        Args:
            project_description: Project description
            objectives: List of objectives
            branch_name: Feature branch name
            base_branch: Base branch
            files_created: List of files created in the project
            
        Returns:
            PR information dict or None
        """
        title = f"feat: {project_description[:50]}"
        if len(project_description) > 50:
            title += "..."
        
        body = self._generate_pr_body(project_description, objectives, files_created)
        
        return self.create_pull_request(title, body, branch_name, base_branch)
    
    def _generate_pr_body(self, project_description: str, objectives: List[str], files_created: Optional[List[str]]) -> str:
        """Generate PR body from project information."""
        body = f"## Project: {project_description}\n\n"
        body += "### Objectives\n\n"
        
        for i, obj in enumerate(objectives, 1):
            body += f"{i}. {obj}\n"
        
        body += "\n### Generated Files\n\n"
        if files_created:
            body += "This PR includes the following generated files:\n\n"
            for file in files_created[:20]:  # Limit to 20 files
                body += f"- `{file}`\n"
            if len(files_created) > 20:
                body += f"\n*...and {len(files_created) - 20} more files*\n"
        else:
            body += "*No file list available*\n"
        
        body += "\n### Generated By\n\n"
        body += "This PR was automatically created by the Multi-Agent Development System.\n"
        body += f"\n**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        
        return body
    
    def get_pr_info(self, pr_number: int) -> Optional[Dict[str, Any]]:
        """Get information about an existing PR."""
        if not self.github_token or not self.github_repo:
            return None
        
        try:
            import httpx
            
            url = f"{self.github_api_base}/repos/{self.github_repo}/pulls/{pr_number}"
            headers = {
                "Authorization": f"token {self.github_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            
            response = httpx.get(url, headers=headers, timeout=30)
            
            if response.status_code == 200:
                return response.json()
            else:
                logger.error(f"Failed to get PR info: {response.status_code}")
                return None
        except Exception as e:
            logger.error(f"Error getting PR info: {e}")
            return None


# Singleton instance
_vcs_integration: Optional[VCSIntegration] = None


def get_vcs_integration(workspace_path: str = ".") -> VCSIntegration:
    """Get the singleton VCSIntegration instance."""
    global _vcs_integration
    if _vcs_integration is None:
        _vcs_integration = VCSIntegration(workspace_path)
    return _vcs_integration

