"""
SQLAlchemy data models for Deliverables to Generate: You must output all these deliverables: A. Documentation: Full system architecture diagram (Mermaid + explanation). ERD (database schema) diagram. API specification (REST + WebSocket). Data model definitions. Requirements document. DevOps and deployment guide.
Generated by CoderAgent
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
from typing import Dict, Any

Base = declarative_base()


class DocumentationDeliverablesGenerateYou(Base):
    """
    SQLAlchemy model representing Deliverables to Generate: You must output all these deliverables: A. Documentation: Full system architecture diagram (Mermaid + explanation). ERD (database schema) diagram. API specification (REST + WebSocket). Data model definitions. Requirements document. DevOps and deployment guide.
    """
    __tablename__ = 'documentation_deliverables_generate_you'

    id = Column(Integer, primary_key=True, autoincrement=True)
    tenant_id = Column(String(255), nullable=False, index=True)  # Multi-tenant support
    name = Column(String(255), nullable=False)
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f'<DocumentationDeliverablesGenerateYou(id={self.id}, name={self.name})>'

    def to_dict(self) -> Dict[str, Any]:
        """Convert model to dictionary."""
        return {
            'id': self.id,
            'tenant_id': self.tenant_id,
            'name': self.name,
            'description': self.description,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]):
        """Create model instance from dictionary."""
        return cls(
            tenant_id=data.get('tenant_id'),
            name=data.get('name'),
            description=data.get('description')
        )

