"""
Odoo v18 JSON-RPC Client
Generated by IntegrationAgent
"""

import requests
from typing import Dict, List, Optional, Any
import logging

logger = logging.getLogger(__name__)


class OdooClient:
    """
    Odoo v18 JSON-RPC API client
    """
    
    def __init__(self, base_url: str, database: str, username: str, api_key: str):
        """
        Initialize Odoo client.
        
        Args:
            base_url: Odoo instance URL (e.g., https://odoo.example.com)
            database: Database name
            username: Odoo username
            api_key: API key or password
        """
        self.base_url = base_url.rstrip("/")
        self.database = database
        self.username = username
        self.api_key = api_key
        self.uid = None
        self.session = requests.Session()
        
        # Authenticate
        self._authenticate()
    
    def _authenticate(self):
        """Authenticate and get user ID."""
        try:
            response = self._call("common", "authenticate", [
                self.database,
                self.username,
                self.api_key,
                {}
            ])
            self.uid = response
        except Exception as e:
            logger.error(f"Failed to authenticate with Odoo: {str(e)}")
            raise
    
    def _call(self, service: str, method: str, params: List) -> Any:
        """
        Make JSON-RPC call to Odoo.
        
        Args:
            service: RPC service (common, object, etc.)
            method: RPC method
            params: Method parameters
            
        Returns:
            Response data
        """
        url = f"{self.base_url}/jsonrpc"
        
        payload = {
            "jsonrpc": "2.0",
            "method": "call",
            "params": {
                "service": service,
                "method": method,
                "args": params
            },
            "id": 1
        }
        
        response = self.session.post(url, json=payload)
        response.raise_for_status()
        
        result = response.json()
        if "error" in result:
            raise Exception(f"Odoo RPC error: {result['error']}")
        
        return result.get("result")
    
    def search_read(self, model: str, domain: List, fields: List[str], 
                   offset: int = 0, limit: int = None) -> List[Dict]:
        """
        Search and read records.
        
        Args:
            model: Odoo model name (e.g., "res.partner")
            domain: Search domain
            fields: Fields to return
            offset: Offset for pagination
            limit: Limit for pagination
            
        Returns:
            List of records
        """
        params = [self.database, self.uid, self.api_key, model, "search_read", domain, fields]
        
        if limit:
            params.extend([offset, limit])
        
        return self._call("object", "execute_kw", params)
    
    def create(self, model: str, values: Dict) -> int:
        """
        Create a new record.
        
        Args:
            model: Odoo model name
            values: Field values
            
        Returns:
            Created record ID
        """
        params = [self.database, self.uid, self.api_key, model, "create", [values]]
        return self._call("object", "execute_kw", params)
    
    def write(self, model: str, record_id: int, values: Dict) -> bool:
        """
        Update a record.
        
        Args:
            model: Odoo model name
            record_id: Record ID
            values: Updated field values
            
        Returns:
            True if successful
        """
        params = [self.database, self.uid, self.api_key, model, "write", [[record_id], values]]
        return self._call("object", "execute_kw", params)
    
    def unlink(self, model: str, record_ids: List[int]) -> bool:
        """
        Delete records.
        
        Args:
            model: Odoo model name
            record_ids: List of record IDs to delete
            
        Returns:
            True if successful
        """
        params = [self.database, self.uid, self.api_key, model, "unlink", [record_ids]]
        return self._call("object", "execute_kw", params)
    
    def call_method(self, model: str, method_name: str, record_ids: List[int], *args) -> Any:
        """
        Call a custom method on records.
        
        Args:
            model: Odoo model name
            method_name: Method name
            record_ids: Record IDs
            *args: Additional arguments
            
        Returns:
            Method result
        """
        params = [self.database, self.uid, self.api_key, model, method_name, record_ids]
        params.extend(args)
        return self._call("object", "execute_kw", params)

