# Azure Application Insights Configuration
# Generated by InfrastructureAgent

resource "azurerm_application_insights" "q2o" {
  name                = "${var.project_name}-appinsights"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  application_type    = "web"
}

# Alert for API 5xx spikes
resource "azurerm_monitor_metric_alert" "api_5xx_spike" {
  name                = "${var.project_name}-api-5xx-spike"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_application_insights.q2o.id]
  description         = "Alert on API 5xx error spikes"

  criteria {
    metric_namespace = "Microsoft.Insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 10
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}

# Alert for WAF blocks
resource "azurerm_monitor_metric_alert" "waf_blocks" {
  name                = "${var.project_name}-waf-blocks"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_frontdoor_firewall_policy.q2o_waf.id]
  description         = "Alert on WAF blocks"

  criteria {
    metric_namespace = "Microsoft.Network/frontdoorWebApplicationFirewallPolicies"
    metric_name      = "WebApplicationFirewallRequestCount"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 50
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}

resource "azurerm_monitor_action_group" "main" {
  name                = "${var.project_name}-alerts"
  resource_group_name = azurerm_resource_group.main.name
  short_name          = "q2o-alerts"

  email_receiver {
    name          = "admin"
    email_address = var.alert_email
  }
}

output "app_insights_instrumentation_key" {
  value     = azurerm_application_insights.q2o.instrumentation_key
  sensitive = true
}

output "app_insights_connection_string" {
  value     = azurerm_application_insights.q2o.connection_string
  sensitive = true
}
