"""
QuickBooks Online API Client - FULL MIGRATION SUPPORT
Generated by IntegrationAgent
Supports ALL QuickBooks Online entities for complete data migration
"""

import requests
from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)

QBO_API_BASE = "https://sandbox-quickbooks.api.intuit.com/v3"  # Use production URL for live
QBO_PROD_BASE = "https://quickbooks.api.intuit.com/v3"


class QBOFullClient:
    """
    QuickBooks Online API client with FULL entity support.
    Supports all 40+ QBO entities for complete migration.
    """
    
    def __init__(self, realm_id: str, access_token: str, production: bool = False):
        """
        Initialize QBO client.
        
        Args:
            realm_id: QuickBooks company ID
            access_token: OAuth access token
            production: Use production API (default: sandbox)
        """
        self.realm_id = realm_id
        self.access_token = access_token
        self.base_url = QBO_PROD_BASE if production else QBO_API_BASE
        self.headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Accept": "application/json",
            "Content-Type": "application/json"
        }
    
    def _make_request(self, method: str, endpoint: str, data: Optional[Dict] = None, 
                     params: Optional[Dict] = None) -> Dict:
        """
        Make API request to QuickBooks.
        
        Args:
            method: HTTP method
            endpoint: API endpoint
            data: Request body data
            params: Query parameters
            
        Returns:
            Response JSON
        """
        url = f"{self.base_url}/company/{self.realm_id}/{endpoint}"
        
        response = requests.request(
            method=method,
            url=url,
            headers=self.headers,
            json=data,
            params=params
        )
        
        response.raise_for_status()
        return response.json()
    
    def query(self, query: str) -> List[Dict]:
        """
        Execute QuickBooks query (SQL-like syntax).
        
        Args:
            query: QuickBooks query string
            
        Returns:
            List of entities
        """
        response = self._make_request("GET", f"query", params={"query": query})
        query_response = response.get("QueryResponse", {})
        
        # QBO returns results in different keys depending on entity type
        for key in query_response:
            if isinstance(query_response[key], list):
                return query_response[key]
        
        return []
    
    def get_entity_by_id(self, entity_type: str, entity_id: str) -> Dict:
        """
        Get entity by ID.
        
        Args:
            entity_type: Entity type (e.g., "Customer", "Vendor")
            entity_id: Entity ID
            
        Returns:
            Entity data
        """
        endpoint = entity_type.lower()
        response = self._make_request("GET", f"{endpoint}/{entity_id}")
        return response.get(entity_type, {})
    
    def create_entity(self, entity_type: str, entity_data: Dict) -> Dict:
        """
        Create an entity.
        
        Args:
            entity_type: Entity type
            entity_data: Entity data
            
        Returns:
            Created entity
        """
        endpoint = entity_type.lower()
        response = self._make_request("POST", endpoint, {entity_type: entity_data})
        return response.get(entity_type, {})
    
    def update_entity(self, entity_type: str, entity_id: str, sync_token: str, data: Dict) -> Dict:
        """
        Update an entity.
        
        Args:
            entity_type: Entity type
            entity_id: Entity ID
            sync_token: Sync token from previous read
            data: Updated entity data
            
        Returns:
            Updated entity
        """
        endpoint = entity_type.lower()
        data["Id"] = entity_id
        data["SyncToken"] = sync_token
        response = self._make_request("POST", endpoint, {entity_type: data})
        return response.get(entity_type, {})
    
    # =====================================================================
    # NAME LIST ENTITIES (Master Data)
    # =====================================================================
    
    def get_company_info(self) -> Dict:
        """Get company information."""
        return self._make_request("GET", "companyinfo/1")
    
    def get_preferences(self) -> Dict:
        """Get company preferences."""
        return self._make_request("GET", "preferences")
    
    def get_customers(self, max_results: int = 1000) -> List[Dict]:
        """Get all customers."""
        return self.query(f"SELECT * FROM Customer MAXRESULTS {max_results}")
    
    def get_vendors(self, max_results: int = 1000) -> List[Dict]:
        """Get all vendors."""
        return self.query(f"SELECT * FROM Vendor MAXRESULTS {max_results}")
    
    def get_employees(self, max_results: int = 1000) -> List[Dict]:
        """Get all employees."""
        return self.query(f"SELECT * FROM Employee MAXRESULTS {max_results}")
    
    def get_accounts(self, max_results: int = 1000) -> List[Dict]:
        """Get chart of accounts."""
        return self.query(f"SELECT * FROM Account MAXRESULTS {max_results}")
    
    def get_items(self, max_results: int = 1000) -> List[Dict]:
        """Get all items (products/services)."""
        return self.query(f"SELECT * FROM Item MAXRESULTS {max_results}")
    
    def get_classes(self, max_results: int = 1000) -> List[Dict]:
        """Get all classes."""
        return self.query(f"SELECT * FROM Class MAXRESULTS {max_results}")
    
    def get_departments(self, max_results: int = 1000) -> List[Dict]:
        """Get all departments."""
        return self.query(f"SELECT * FROM Department MAXRESULTS {max_results}")
    
    def get_payment_methods(self, max_results: int = 1000) -> List[Dict]:
        """Get all payment methods."""
        return self.query(f"SELECT * FROM PaymentMethod MAXRESULTS {max_results}")
    
    def get_terms(self, max_results: int = 1000) -> List[Dict]:
        """Get all payment terms."""
        return self.query(f"SELECT * FROM Term MAXRESULTS {max_results}")
    
    def get_tax_codes(self, max_results: int = 1000) -> List[Dict]:
        """Get all tax codes."""
        return self.query(f"SELECT * FROM TaxCode MAXRESULTS {max_results}")
    
    def get_tax_rates(self, max_results: int = 1000) -> List[Dict]:
        """Get all tax rates."""
        return self.query(f"SELECT * FROM TaxRate MAXRESULTS {max_results}")
    
    # =====================================================================
    # TRANSACTION ENTITIES (Sales)
    # =====================================================================
    
    def get_invoices(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all invoices."""
        query = f"SELECT * FROM Invoice"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_sales_receipts(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all sales receipts."""
        query = f"SELECT * FROM SalesReceipt"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_estimates(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all estimates."""
        query = f"SELECT * FROM Estimate"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_credit_memos(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all credit memos."""
        query = f"SELECT * FROM CreditMemo"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_refund_receipts(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all refund receipts."""
        query = f"SELECT * FROM RefundReceipt"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_payments(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all customer payments."""
        query = f"SELECT * FROM Payment"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    # =====================================================================
    # TRANSACTION ENTITIES (Purchases)
    # =====================================================================
    
    def get_bills(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all bills."""
        query = f"SELECT * FROM Bill"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_bill_payments(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all bill payments."""
        query = f"SELECT * FROM BillPayment"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_purchase_orders(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all purchase orders."""
        query = f"SELECT * FROM PurchaseOrder"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_vendor_credits(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all vendor credits."""
        query = f"SELECT * FROM VendorCredit"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_purchases(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all purchases (expenses/checks)."""
        query = f"SELECT * FROM Purchase"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    # =====================================================================
    # TRANSACTION ENTITIES (Other)
    # =====================================================================
    
    def get_journal_entries(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all journal entries."""
        query = f"SELECT * FROM JournalEntry"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_transfers(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all transfers."""
        query = f"SELECT * FROM Transfer"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_deposits(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all deposits."""
        query = f"SELECT * FROM Deposit"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    def get_time_activities(self, start_date: Optional[str] = None, max_results: int = 1000) -> List[Dict]:
        """Get all time activities."""
        query = f"SELECT * FROM TimeActivity"
        if start_date:
            query += f" WHERE MetaData.LastUpdatedTime > '{start_date}'"
        query += f" MAXRESULTS {max_results}"
        return self.query(query)
    
    # =====================================================================
    # INVENTORY & TRACKING
    # =====================================================================
    
    def get_inventory_adjustments(self, max_results: int = 1000) -> List[Dict]:
        """Get all inventory adjustments (via Journal Entries)."""
        # Inventory adjustments are typically journal entries
        return self.get_journal_entries(max_results=max_results)
    
    def get_budgets(self, max_results: int = 1000) -> List[Dict]:
        """Get all budgets."""
        return self.query(f"SELECT * FROM Budget MAXRESULTS {max_results}")
    
    # =====================================================================
    # REPORTS (Read-only)
    # =====================================================================
    
    def get_report(self, report_name: str, params: Optional[Dict] = None) -> Dict:
        """
        Get a QuickBooks report.
        
        Args:
            report_name: Report name (e.g., "BalanceSheet", "ProfitAndLoss")
            params: Report parameters (start_date, end_date, etc.)
            
        Returns:
            Report data
        """
        return self._make_request("GET", f"reports/{report_name}", params=params)
    
    def get_balance_sheet(self, date: Optional[str] = None) -> Dict:
        """Get Balance Sheet report."""
        params = {}
        if date:
            params["date"] = date
        return self.get_report("BalanceSheet", params)
    
    def get_profit_and_loss(self, start_date: Optional[str] = None, 
                           end_date: Optional[str] = None) -> Dict:
        """Get Profit & Loss report."""
        params = {}
        if start_date:
            params["start_date"] = start_date
        if end_date:
            params["end_date"] = end_date
        return self.get_report("ProfitAndLoss", params)
    
    def get_general_ledger(self, start_date: Optional[str] = None, 
                           end_date: Optional[str] = None) -> Dict:
        """Get General Ledger report."""
        params = {}
        if start_date:
            params["start_date"] = start_date
        if end_date:
            params["end_date"] = end_date
        return self.get_report("GeneralLedger", params)
    
    # =====================================================================
    # BATCH OPERATIONS (Efficient bulk operations)
    # =====================================================================
    
    def batch_request(self, operations: List[Dict]) -> List[Dict]:
        """
        Execute batch operations (up to 30 operations per batch).
        
        Args:
            operations: List of operation dicts with 'bId', 'operation', 'entity', 'data'
            
        Returns:
            List of results
        """
        batch_data = {"BatchItemRequest": operations}
        response = self._make_request("POST", "batch", batch_data)
        return response.get("BatchItemResponse", [])
    
    # =====================================================================
    # CHANGE DATA CAPTURE (Incremental sync)
    # =====================================================================
    
    def get_change_data_capture(self, entities: List[str], changed_since: str) -> Dict:
        """
        Get entities that changed since a specific time (CDC).
        
        Args:
            entities: List of entity types to track
            changed_since: ISO datetime string
            
        Returns:
            Dict with changed entities
        """
        entities_str = ",".join(entities)
        return self._make_request("GET", "cdc", params={
            "entities": entities_str,
            "changedSince": changed_since
        })
    
    # =====================================================================
    # UTILITY METHODS
    # =====================================================================
    
    def get_all_entities(self) -> Dict[str, List[Dict]]:
        """
        Get ALL entities from QuickBooks for complete migration.
        
        Returns:
            Dictionary with entity type as key and list of entities as value
        """
        logger.info("Starting FULL QuickBooks data extraction...")
        
        all_data = {}
        
        # Master data (Name Lists)
        logger.info("Extracting master data...")
        all_data["customers"] = self.get_customers()
        all_data["vendors"] = self.get_vendors()
        all_data["employees"] = self.get_employees()
        all_data["accounts"] = self.get_accounts()
        all_data["items"] = self.get_items()
        all_data["classes"] = self.get_classes()
        all_data["departments"] = self.get_departments()
        all_data["payment_methods"] = self.get_payment_methods()
        all_data["terms"] = self.get_terms()
        all_data["tax_codes"] = self.get_tax_codes()
        all_data["tax_rates"] = self.get_tax_rates()
        
        # Sales transactions
        logger.info("Extracting sales transactions...")
        all_data["invoices"] = self.get_invoices()
        all_data["sales_receipts"] = self.get_sales_receipts()
        all_data["estimates"] = self.get_estimates()
        all_data["credit_memos"] = self.get_credit_memos()
        all_data["refund_receipts"] = self.get_refund_receipts()
        all_data["payments"] = self.get_payments()
        
        # Purchase transactions
        logger.info("Extracting purchase transactions...")
        all_data["bills"] = self.get_bills()
        all_data["bill_payments"] = self.get_bill_payments()
        all_data["purchase_orders"] = self.get_purchase_orders()
        all_data["vendor_credits"] = self.get_vendor_credits()
        all_data["purchases"] = self.get_purchases()
        
        # Other transactions
        logger.info("Extracting other transactions...")
        all_data["journal_entries"] = self.get_journal_entries()
        all_data["transfers"] = self.get_transfers()
        all_data["deposits"] = self.get_deposits()
        all_data["time_activities"] = self.get_time_activities()
        
        # Company info
        all_data["company_info"] = [self.get_company_info()]
        all_data["preferences"] = [self.get_preferences()]
        
        logger.info("FULL QuickBooks data extraction complete!")
        
        # Log statistics
        for entity_type, entities in all_data.items():
            logger.info(f"{entity_type}: {len(entities)} records")
        
        return all_data


